In [1]:
import pandas as pd

In [2]:
d1 = pd.read_csv(r"C:\Users\Mahoor Zehra\OneDrive\Desktop\train.csv")

In [ ]:
print(d1.loc[2,'Name'] )           #label-based indexing
d1.iloc[2,3]                       #position-based indexing

Sorting:

In [ ]:
d1.sort_values(by='Age')         #by default, ascending

In [ ]:
d1.sort_values(by='Age', ascending = False)

In [ ]:
d1.sort_values(by='Fare', inplace=True)             # changes the original
d1

In [ ]:
d1.iloc[815,3] = 'abc'                          #Updating using iloc[]

In [ ]:
d1[d1['Name'].str.contains('abc', na=False)]    #Searching for text using str.contains()

Filtering

In [ ]:
female_data = d1[d1['Sex'] == 'female']
female_data

In [ ]:
adult = d1[d1['Age'] > 18]
adult

A list of females who were travelling in 1st class under 18 and who survived

In [ ]:
female_rich_children = d1[
    (d1['Sex'] == 'female') &
    (d1['Pclass'] == 1) &
    (d1['Age']  < 18) &
    (d1['Survived'] == 1)
]
female_rich_children

To change a value without knowing the index or labels (no iloc or loc)

In [ ]:
d1.replace('Heikkinen, Miss. Laina', 'hello')

Renaming a column

In [ ]:
d1.rename(columns = {'Sex' : 'Gender'})

Unique values:

In [ ]:
d1['Age'].nunique()

To delete missing values:

In [ ]:
d1.dropna(subset= ['Age'])

To invert: 1 -> 0 & 0 -> 1

In [ ]:
d1['Survived'] = d1['Survived'].map({0: 'Not survived',  1: 'Survived'})

To fill null values and fill them up:

In [ ]:
d1['Age'].isnull().sum()
d1['Age'] = d1['Age'].fillna(d1['Age'].mean())

In [ ]:
d1['Embarked'] = d1['Embarked'].fillna('Unknown')

In [ ]:
d1['Embarked'].isnull().sum()

Group by :

In [ ]:
d1['Survived'].value_counts()           # how many times 0 and 1 occured

In [ ]:
d1.groupby('Sex')['Survived'].sum()

In [ ]:
d1.groupby('Sex')['Survived'].mean()         #  mean() calculates the average survival value for each sex group.

233 and 109 are representing the survivors because through sum we added all the 1s i.e. survivors. We can count deaths by reversing the encoding

In [ ]:
d1['Survived'] = d1['Survived'].map({0:1, 1:0})

In [ ]:
d1.groupby('Sex')['Survived'].sum()

In [ ]:
d1.groupby('Sex')['Survived'].mean()               #after reversing the encoding, the mean would represent the death rate.

We want to count how many male and female passengers belonged to each passenger class.

In [ ]:
d1.groupby('Pclass')['Sex'].sum()                       # textual data can't be added: summing text concatenates strings

In [ ]:
d1['Sex'] = d1['Sex'].map({"female":0,"male":1})

In [ ]:
d1.groupby('Pclass')['Sex'].sum()               #gives male count

In [ ]:
d1.groupby(['Pclass', 'Sex']).size()

In [ ]:
d1.groupby('Pclass')['Survived'].sum()

In [ ]:
d1['Survived'].value_counts()

Working on duplicates

In [ ]:
d1.duplicated()             # counts null indices

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [6]:
d1.duplicated().sum()

np.int64(0)

In [ ]:
d1[d1['Age'].duplicated()]                  # checks null values in Age column

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
d1.drop_duplicates(subset = ['Age'], inplace = True)            # drops duplicates

In [15]:
d1.groupby(['Sex', 'Pclass'])['Survived'].sum()

Sex     Pclass
female  1         8
        2         7
        3         8
male    1         4
        2         3
        3         2
Name: Survived, dtype: int64

In [ ]:
d1['Adult'] = d1['Age'] > 18
d1.sample()                         # provides a random row

In [20]:
d1['Age_Groups'] = d1['Age'].apply(
    lambda age: 'child' if pd.notna(age) and age < 18
    else 'Adult' if pd.notna(age)
    else 'unknown'
)

In [21]:
d1.sample()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Adult,Age_Groups
53,54,1,2,"Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...",female,29.0,1,0,2926,26.0,NaN,S,True,Adult